import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { mkdtemp } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { createContextPackage } from "../src/pack.js";

async function createTempRepo(): Promise<string> {
  return mkdtemp(join(tmpdir(), "repo-context-pack-"));
}

describe("createContextPackage", () => {
  it("supports dry-run without writing files", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"dry-run-app\"}", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false
    });

    expect(result.writes.every((write) => write.status === "planned")).toBe(true);
    expect(existsSync(join(root, "AGENTS.md"))).toBe(false);
    expect(existsSync(join(root, ".repo-context", "index.json"))).toBe(false);
  });

  it("writes markdown and JSON outputs with relative paths", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({ name: "write-app", scripts: { test: "vitest run" } }),
      "utf8"
    );
    await writeFile(join(root, "src", "index.ts"), "export {};\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "cursor",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.map((write) => write.status)).toEqual(["written", "written", "written", "written"]);
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Generated by Repo Context CLI");
    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.schemaVersion).toBe(1);
    expect(index.generatedBy).toBe("Repo Context CLI");
    expect(index.generatedAt).toEqual(expect.any(String));
    expect(index.root).toBe(".");
    expect(index.target).toBe("cursor");
    expect(index.project.name).toBe("write-app");
    expect(index.project.monorepo).toEqual({
      detected: false,
      tools: [],
      workspaceGlobs: [],
      packageRoots: []
    });
    expect(index.commands.test).toBe("npm test");
    expect(index.excluded).toEqual(expect.any(Array));
    expect(index.truncated).toBe(false);
    expect(index.warnings).toEqual(expect.any(Array));
    expect(index.signals).toContainEqual(expect.objectContaining({ source: "package.json" }));
    expect(index.files).toContainEqual(expect.objectContaining({ path: "src/index.ts", kind: "source" }));
  });

  it("writes monorepo facts into index.json", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "packages", "ui"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({ name: "pack-monorepo", workspaces: ["packages/*"] }),
      "utf8"
    );
    await writeFile(join(root, "packages", "ui", "package.json"), "{\"name\":\"ui\"}", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.project.monorepo).toEqual({
      detected: true,
      tools: ["npm-workspaces"],
      workspaceGlobs: ["packages/*"],
      packageRoots: ["packages/ui"]
    });
  });

  it("writes non-JavaScript language stacks without invented commands", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "pyproject.toml"), "[project]\nname = \"python-app\"\n", "utf8");
    await writeFile(join(root, "Cargo.toml"), "[package]\nname = \"rust-app\"\n", "utf8");
    await writeFile(join(root, "go.mod"), "module example.com/go-app\n", "utf8");
    await writeFile(join(root, "pom.xml"), "<project />\n", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.project.stacks).toEqual(["python", "rust", "go", "java"]);
    expect(index.commands).toEqual({
      install: null,
      dev: null,
      build: null,
      test: null,
      lint: null,
      format: null
    });
    expect(index.signals).toContainEqual({
      source: "pyproject.toml",
      description: "Detected Python project"
    });
    expect(index.signals).toContainEqual({
      source: "Cargo.toml",
      description: "Detected Rust project"
    });
    expect(index.signals).toContainEqual({
      source: "go.mod",
      description: "Detected Go project"
    });
    expect(index.signals).toContainEqual({
      source: "pom.xml",
      description: "Detected Java project"
    });
  });

  it("does not overwrite user files unless force is enabled", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"safe-app\"}", "utf8");
    await writeFile(join(root, "AGENTS.md"), "# Hand written rules\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("skipped");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toBe("# Hand written rules\n");
  });

  it("does not treat arbitrary marker text as a generated file", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"marker-app\"}", "utf8");
    await writeFile(
      join(root, "AGENTS.md"),
      "# Hand written rules\n\nThis file discusses Generated by Repo Context CLI.\n",
      "utf8"
    );

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("skipped");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Hand written rules");
  });

  it("overwrites user files only when force is enabled", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"force-app\"}", "utf8");
    await writeFile(join(root, "AGENTS.md"), "# Hand written rules\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: true
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("overwritten");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Generated by Repo Context CLI");
  });

  it("rejects output directories outside the repository", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"escape-app\"}", "utf8");

    await expect(
      createContextPackage({
        root,
        target: "codex",
        outputDir: "../outside",
        maxFiles: 500,
        dryRun: true,
        force: false
      })
    ).rejects.toThrow("--output must be a relative directory inside the repository");
  });

  it("still generates a basic package for non-JS repositories without inventing commands", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "README.md"), "# Notes\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false
    });

    expect(result.context.project.stacks).toEqual([]);
    expect(result.context.commands.install).toBeNull();
    expect(result.context.commands.test).toBeNull();
    expect(result.context.files).toContainEqual(expect.objectContaining({ path: "README.md" }));
    expect(result.warnings).toContain("No package.json detected; command inference is limited.");
  });
});
