import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { mkdtemp } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { createContextPackage } from "../src/pack.js";

async function createTempRepo(): Promise<string> {
  return mkdtemp(join(tmpdir(), "repo-context-pack-"));
}

describe("createContextPackage", () => {
  it("supports dry-run without writing files", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"dry-run-app\"}", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false
    });

    expect(result.writes.every((write) => write.status === "planned")).toBe(true);
    expect(existsSync(join(root, "AGENTS.md"))).toBe(false);
    expect(existsSync(join(root, ".repo-context", "index.json"))).toBe(false);
    expect(existsSync(join(root, ".repo-context", "report.html"))).toBe(false);
  });

  it("writes markdown and JSON outputs with relative paths", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({ name: "write-app", scripts: { test: "vitest run" } }),
      "utf8"
    );
    await writeFile(join(root, "src", "index.ts"), "export {};\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "cursor",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.map((write) => write.status)).toEqual(["written", "written", "written", "written"]);
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Generated by Repo Context CLI");
    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.schemaVersion).toBe(1);
    expect(index.generatedBy).toBe("Repo Context CLI");
    expect(index.generatedAt).toEqual(expect.any(String));
    expect(index.root).toBe(".");
    expect(index.target).toBe("cursor");
    expect(index.project.name).toBe("write-app");
    expect(index.project.monorepo).toEqual({
      detected: false,
      tools: [],
      workspaceGlobs: [],
      packageRoots: []
    });
    expect(index.commands.test).toBe("npm test");
    expect(index.excluded).toEqual(expect.any(Array));
    expect(index.truncated).toBe(false);
    expect(index.warnings).toEqual(expect.any(Array));
    expect(index.signals).toContainEqual(expect.objectContaining({ source: "package.json" }));
    expect(index.files).toContainEqual(expect.objectContaining({ path: "src/index.ts", kind: "source" }));
    expect(index.redactions).toEqual({
      secretLikePaths: 0,
      commandValues: 0
    });
  });

  it("writes final context summary into index.json", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(join(root, "package.json"), "{\"name\":\"summary-app\"}", "utf8");
    await writeFile(join(root, "src", "small.ts"), "export const small = 1;\n", "utf8");
    await writeFile(join(root, "src", "large.ts"), "export const large = 'aaaaaaaaaa';\n", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const generatedPaths = ["AGENTS.md", "PROJECT_MAP.md", "TESTING.md", ".repo-context/index.json"];
    const generatedContents = await Promise.all(
      generatedPaths.map((path) => readFile(join(root, path), "utf8"))
    );
    const index = JSON.parse(generatedContents[3] ?? "");
    const generatedCharacters = generatedContents.reduce((total, content) => total + content.length, 0);
    const generatedBytes = generatedContents.reduce(
      (total, content) => total + Buffer.byteLength(content, "utf8"),
      0
    );

    expect(index.summary.scope).toBe("planned-generated-content");
    expect(index.summary.indexedFiles).toBe(3);
    expect(index.summary.indexedBytes).toBe(
      Buffer.byteLength("{\"name\":\"summary-app\"}", "utf8") +
        Buffer.byteLength("export const small = 1;\n", "utf8") +
        Buffer.byteLength("export const large = 'aaaaaaaaaa';\n", "utf8")
    );
    expect(index.summary.generatedFiles).toBe(4);
    expect(index.summary.generatedBytes).toBe(generatedBytes);
    expect(index.summary.estimatedTokens).toBe(Math.ceil(generatedCharacters / 4));
    expect(index.summary.largestFiles[0]).toEqual({
      path: "src/large.ts",
      kind: "source",
      sizeBytes: Buffer.byteLength("export const large = 'aaaaaaaaaa';\n", "utf8")
    });
  });

  it("renders context summary in PROJECT_MAP.md", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "README.md"), "# Summary\n", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const projectMap = await readFile(join(root, "PROJECT_MAP.md"), "utf8");
    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));

    expect(projectMap).toContain("## Context Summary");
    expect(projectMap).toContain(`- Indexed files: ${index.summary.indexedFiles}`);
    expect(projectMap).toContain(`- Indexed bytes: ${index.summary.indexedBytes}`);
    expect(projectMap).toContain(`- Generated files (planned): ${index.summary.generatedFiles}`);
    expect(projectMap).toContain(`- Generated bytes (planned): ${index.summary.generatedBytes}`);
    expect(projectMap).toContain(`- Estimated tokens (planned): ${index.summary.estimatedTokens}`);
    expect(projectMap).toContain("- Largest indexed files:");
    expect(projectMap).toContain("- `README.md` (documentation, 10 bytes)");
    expect(projectMap).toContain("## Redactions");
    expect(projectMap).toContain("- Secret-like paths redacted: 0");
    expect(projectMap).toContain("- Command values redacted: 0");
  });

  it("labels summary generated counts as planned when user-authored files are skipped", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"skip-summary-app\"}", "utf8");
    await writeFile(join(root, "AGENTS.md"), "# Hand written rules\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("skipped");
    expect(index.summary.scope).toBe("planned-generated-content");
    expect(index.summary.generatedFiles).toBe(4);
  });

  it("writes an optional static HTML report when requested", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "packages", "api"), { recursive: true });
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({
        name: "html-report-app",
        workspaces: ["packages/*"],
        scripts: {
          build: "vite build",
          test: "vitest run"
        }
      }),
      "utf8"
    );
    await writeFile(join(root, "src", "index.ts"), "export const app = true;\n", "utf8");
    await writeFile(join(root, "README.md"), "# HTML report app\n", "utf8");
    await writeFile(join(root, "packages", "api", "package.json"), "{\"name\":\"api\"}", "utf8");
    await writeFile(join(root, ".env"), "TOKEN=secret\n", "utf8");

    const options = {
      root,
      target: "codex" as const,
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false,
      htmlReport: true
    };

    const result = await createContextPackage(options);

    expect(result.writes.map((write) => write.path)).toContain(".repo-context/report.html");
    const report = await readFile(join(root, ".repo-context", "report.html"), "utf8");
    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));

    expect(report).toContain("repo-context-cli:generated");
    expect(report).toContain("<title>Repo Context Report - html-report-app</title>");
    expect(report).toContain("Project Summary");
    expect(report).toContain("html-report-app");
    expect(report).toContain("npm run build");
    expect(report).toContain("npm test");
    expect(report).toContain("Secret-like paths redacted");
    expect(report).toContain("Monorepo");
    expect(report).toContain("npm-workspaces");
    expect(report).toContain("Largest Files");
    expect(report).toContain("File Categories");
    expect(report).not.toContain("<script");
    expect(report).not.toContain(".env");
    expect(index.summary.generatedFiles).toBe(5);
  });

  it("plans the optional HTML report during dry-run without writing it", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"dry-report-app\"}", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false,
      htmlReport: true
    });

    expect(result.writes.find((write) => write.path === ".repo-context/report.html")?.status).toBe("planned");
    expect(existsSync(join(root, ".repo-context", "report.html"))).toBe(false);
  });

  it("does not overwrite a user-authored HTML report unless force is enabled", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, ".repo-context"), { recursive: true });
    await writeFile(join(root, "package.json"), "{\"name\":\"safe-report-app\"}", "utf8");
    await writeFile(join(root, ".repo-context", "report.html"), "<!doctype html><p>hand written</p>\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false,
      htmlReport: true
    });

    expect(result.writes.find((write) => write.path === ".repo-context/report.html")?.status).toBe("skipped");
    expect(await readFile(join(root, ".repo-context", "report.html"), "utf8")).toBe(
      "<!doctype html><p>hand written</p>\n"
    );
  });

  it("escapes repository data in the optional HTML report", async () => {
    const root = await createTempRepo();
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({
        name: "<script>alert('x')</script>",
        workspaces: ["packages/<img src=x onerror=alert(1)>"],
        scripts: {
          test: "echo \"<img src=x onerror=alert(1)>\""
        }
      }),
      "utf8"
    );

    const options = {
      root,
      target: "codex" as const,
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false,
      htmlReport: true
    };

    await createContextPackage(options);

    const report = await readFile(join(root, ".repo-context", "report.html"), "utf8");
    expect(report).toContain("&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;");
    expect(report).toContain("&lt;img src=x onerror=alert(1)&gt;");
    expect(report).not.toContain("<script>");
    expect(report).not.toContain("<img src=x");
  });

  it("writes monorepo facts into index.json", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "packages", "ui"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({ name: "pack-monorepo", workspaces: ["packages/*"] }),
      "utf8"
    );
    await writeFile(join(root, "packages", "ui", "package.json"), "{\"name\":\"ui\"}", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.project.monorepo).toEqual({
      detected: true,
      tools: ["npm-workspaces"],
      workspaceGlobs: ["packages/*"],
      packageRoots: ["packages/ui"]
    });
  });

  it("writes non-JavaScript language stacks without invented commands", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "pyproject.toml"), "[project]\nname = \"python-app\"\n", "utf8");
    await writeFile(join(root, "Cargo.toml"), "[package]\nname = \"rust-app\"\n", "utf8");
    await writeFile(join(root, "go.mod"), "module example.com/go-app\n", "utf8");
    await writeFile(join(root, "pom.xml"), "<project />\n", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const index = JSON.parse(await readFile(join(root, ".repo-context", "index.json"), "utf8"));
    expect(index.project.stacks).toEqual(["python", "rust", "go", "java"]);
    expect(index.commands).toEqual({
      install: null,
      dev: null,
      build: null,
      test: null,
      lint: null,
      format: null
    });
    expect(index.signals).toContainEqual({
      source: "pyproject.toml",
      description: "Detected Python project"
    });
    expect(index.signals).toContainEqual({
      source: "Cargo.toml",
      description: "Detected Rust project"
    });
    expect(index.signals).toContainEqual({
      source: "go.mod",
      description: "Detected Go project"
    });
    expect(index.signals).toContainEqual({
      source: "pom.xml",
      description: "Detected Java project"
    });
  });

  it("does not overwrite user files unless force is enabled", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"safe-app\"}", "utf8");
    await writeFile(join(root, "AGENTS.md"), "# Hand written rules\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("skipped");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toBe("# Hand written rules\n");
  });

  it("does not treat arbitrary marker text as a generated file", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"marker-app\"}", "utf8");
    await writeFile(
      join(root, "AGENTS.md"),
      "# Hand written rules\n\nThis file discusses Generated by Repo Context CLI.\n",
      "utf8"
    );

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("skipped");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Hand written rules");
  });

  it("overwrites user files only when force is enabled", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"force-app\"}", "utf8");
    await writeFile(join(root, "AGENTS.md"), "# Hand written rules\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: true
    });

    expect(result.writes.find((write) => write.path === "AGENTS.md")?.status).toBe("overwritten");
    expect(await readFile(join(root, "AGENTS.md"), "utf8")).toContain("Generated by Repo Context CLI");
  });

  it("rejects output directories outside the repository", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "package.json"), "{\"name\":\"escape-app\"}", "utf8");

    await expect(
      createContextPackage({
        root,
        target: "codex",
        outputDir: "../outside",
        maxFiles: 500,
        dryRun: true,
        force: false
      })
    ).rejects.toThrow("--output must be a relative directory inside the repository");
  });

  it("still generates a basic package for non-JS repositories without inventing commands", async () => {
    const root = await createTempRepo();
    await writeFile(join(root, "README.md"), "# Notes\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false
    });

    expect(result.context.project.stacks).toEqual([]);
    expect(result.context.commands.install).toBeNull();
    expect(result.context.commands.test).toBeNull();
    expect(result.context.files).toContainEqual(expect.objectContaining({ path: "README.md" }));
    expect(result.warnings).toContain("No package.json detected; command inference is limited.");
  });

  it("redacts secret-like paths from generated context", async () => {
    const root = await createTempRepo();
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({
        name: "redaction-app",
        scripts: {
          build: "vite build",
          test: "vitest run"
        }
      }),
      "utf8"
    );
    await writeFile(join(root, ".env"), "API_KEY=super-secret\n", "utf8");

    const result = await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: true,
      force: false
    });

    expect(result.context.files.map((file) => file.path)).toEqual(["package.json"]);
    expect(result.context.commands.build).toBe("npm run build");
    expect(result.context.commands.test).toBe("npm test");
    expect(result.context.redactions).toEqual({
      secretLikePaths: 1,
      commandValues: 0
    });
    expect(result.warnings).toContain("Redacted 1 secret-like path from the context package.");
    expect(result.warnings).not.toContain("Redacted 2 detected command values from the context package.");
  });

  it("redacts secret-like monorepo path fields from generated context", async () => {
    const root = await createTempRepo();
    await mkdir(join(root, "packages", ".ssh"), { recursive: true });
    await writeFile(
      join(root, "package.json"),
      JSON.stringify({
        name: "monorepo-redaction-app",
        workspaces: ["packages/*", ".env.local/*"]
      }),
      "utf8"
    );
    await writeFile(join(root, "packages", ".ssh", "package.json"), "{\"name\":\"secret-root\"}", "utf8");

    await createContextPackage({
      root,
      target: "codex",
      outputDir: ".repo-context",
      maxFiles: 500,
      dryRun: false,
      force: false
    });

    const indexText = await readFile(join(root, ".repo-context", "index.json"), "utf8");
    const projectMap = await readFile(join(root, "PROJECT_MAP.md"), "utf8");
    const index = JSON.parse(indexText);

    expect(index.project.monorepo.workspaceGlobs).toEqual(["packages/*"]);
    expect(index.project.monorepo.packageRoots).toEqual([]);
    expect(index.redactions.secretLikePaths).toBe(3);
    expect(indexText).not.toContain(".env.local");
    expect(indexText).not.toContain("packages/.ssh");
    expect(projectMap).not.toContain(".env.local");
    expect(projectMap).not.toContain("packages/.ssh");
    expect(projectMap).toContain("- Secret-like paths redacted: 3");
  });
});
