import type { AgentTarget, ProjectCommands, RepositoryContext, ScannedFile } from "../model.js";

export const GENERATED_MARKER = "Generated by Repo Context CLI";
export const GENERATED_HEADER_PREFIX = "<!-- repo-context-cli:generated";

export function renderAgentsMarkdown(context: RepositoryContext): string {
  const targetGuidance = getTargetGuidance(context.target);

  return `${header(context)}
# Agent Instructions

## Project Summary

- Project name: ${context.project.name}
- Detected stacks: ${formatList(context.project.stacks)}
- Package manager: ${context.project.packageManager ?? "not detected"}
- Context target: ${context.target}

## Operating Rules

- Prefer existing project patterns over new abstractions.
- Keep changes scoped to the user request.
- Do not edit generated files, dependency folders, build outputs, or ignored directories unless explicitly requested.
- Run relevant verification commands before claiming completion.
- If a command or directory purpose is unknown, say so instead of guessing.

## Target Guidance

${targetGuidance}

## Common Commands

${renderCommandList(context.commands)}

## Important Files

${renderFileBullets(context.files.slice(0, 20))}
`;
}

export function renderProjectMapMarkdown(context: RepositoryContext): string {
  return `${header(context)}
# Project Map

## Repository Facts

- Project name: ${context.project.name}
- Detected stacks: ${formatList(context.project.stacks)}
- Indexed files: ${context.files.length}${context.truncated ? " (truncated by --max-files)" : ""}
- Excluded directories: ${formatList(context.excluded)}

## Files

${renderFileBullets(context.files)}

## Detection Signals

${context.signals.length > 0 ? context.signals.map((signal) => `- ${signal.source}: ${signal.description}`).join("\n") : "- No strong project signals detected."}

## Notes

- Directory purposes are based on file names and paths only.
- Unknown purposes are not inferred.
`;
}

export function renderTestingMarkdown(context: RepositoryContext): string {
  return `${header(context)}
# Testing and Development Commands

## Detected Commands

${renderCommandList(context.commands)}

## Notes

- Commands are inferred from common project files such as package.json.
- Missing commands are reported as not detected.
- Verify commands locally before relying on them in CI.
`;
}

function header(context: RepositoryContext): string {
  return `${GENERATED_HEADER_PREFIX}; ${GENERATED_MARKER}. Command: repo-context pack --for ${context.target}. Generated at: ${context.generatedAt}. -->\n\n`;
}

function renderCommandList(commands: ProjectCommands): string {
  const rows: Array<[string, string | null]> = [
    ["Install", commands.install],
    ["Development", commands.dev],
    ["Build", commands.build],
    ["Test", commands.test],
    ["Lint", commands.lint],
    ["Format", commands.format]
  ];

  return rows.map(([label, command]) => `- ${label}: ${command ? `\`${command}\`` : "not detected"}`).join("\n");
}

function renderFileBullets(files: ScannedFile[]): string {
  if (files.length === 0) {
    return "- No files indexed.";
  }

  return files.map((file) => `- \`${file.path}\` (${file.kind}, ${file.sizeBytes} bytes)`).join("\n");
}

function formatList(values: string[]): string {
  return values.length > 0 ? values.join(", ") : "not detected";
}

function getTargetGuidance(target: AgentTarget): string {
  switch (target) {
    case "claude":
      return "- Read these files before editing. Use the project commands in this context package for verification.";
    case "cursor":
      return "- Treat this context package as project rules for AI-assisted edits in the editor.";
    case "codex":
      return "- Inspect the relevant files first, preserve unrelated user changes, and verify with the detected commands.";
  }
}
